---

- name: "repo: set git url, path and config"
  set_fact:
    git_repo_url: "{{ git_repo_settings['url'] }}{{ git_repo_items['project'] }}/{{ git_repo_items['repo'] }}.git"
    git_repo_path: "{{ git_repo_settings['dir'] }}/{{ git_repo_items['project'] | lower }}/{{ git_repo_items['dir']|default(git_repo_items['repo']) }}"
    git_repo_config: "{{ git_repo_settings['config'] | default({}) | combine(git_repo_items['config'] | default({})) }}"

- name: "repo: clone / update block"
  block:
  - name: "repo: clone / update task"
    git:
      repo: "{{ git_repo_url }}"
      dest: "{{ git_repo_path }}"
    tags: git-repo-clone
    register: git_clone_result
  rescue:
  - name: "repo: clone-rescue / debug"
    debug:
      msg: "Failed to clone or update {{ git_repo_path }}: {{ git_clone_result['msg'] }}"

  - name: "repo: clone-rescue / append git_failed_repos"
    set_fact:
      git_failed_repos: "{{ git_failed_repos + [{
        'url': git_repo_url,
        'path': git_repo_path,
        'msg': git_clone_result['msg']}] }}"

- name: "repo: set user-name and email"
  git_config:
    name: "{{ git_config_item[0] }}.{{ git_config_item[1] }}"
    repo: "{{ git_repo_path }}"
    scope: local
    value: "{{ git_config_item[2] }}"
  loop: "{{ lookup('2level_dict', git_repo_config) }}"
  loop_control:
    loop_var: git_config_item
  tags: git-repo-config

...
